/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class MentallertIcons {
  MentallertIcons._();

  static const _kFontFam = 'Mentallerts';

  static const IconData attention = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData asset_2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData asset_3 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData asset_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData asset_4 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData twitter_bird = const IconData(0xf303, fontFamily: _kFontFam);
}
